### ISSUE TITLE
unable to render template

### ISSUE THREAD

**Issue by chubchubsancho** [fboender/ansible-cmdb#140]
i've got this error when i run ansible-cmdb -t markdown -d cmdb/ > out/cmdb.md

Whoops, it looks like something went wrong while rendering the template.

The reported error was: AttributeError: 'NoneType' object has no attribute 'items'

The full error was:

    Traceback (most recent call last):
      File "/usr/local/bin/ansible-cmdb", line 165, in <module>
        output = renderer.render(ansible.hosts, params)
      File "/usr/local/lib/python2.7/dist-packages/ansiblecmdb/render.py", line 45, in render
        return self._render_mako(hosts, vars)
      File "/usr/local/lib/python2.7/dist-packages/ansiblecmdb/render.py", line 62, in _render_mako
        return template.render(hosts=hosts, **vars)
      File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 462, in render
        return runtime._render(self, self.callable_, args, data)
      File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 838, in _render
        **_kwargs_for_callable(callable_, data))
      File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 873, in _render_context
        _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
      File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 899, in _exec_template
        callable_(context, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/ansiblecmdb/data/tpl/markdown.tpl", line 95, in render_body
        % for var_name, var_value in host['hostvars'].items():
    AttributeError: 'NoneType' object has no attribute 'items'

The output is probably not correct.

**Comment by fboender** [comment]
Hi chubchubsancho.

Thanks for the bug report. I've committed a change that should fix this. Can you try against the master branch in git?
