### ISSUE TITLE
Python 3.6 issue

### ISSUE THREAD

**Issue by fboender** [fboender/ansible-cmdb#143]
Ansible-cmdb under Python 3.6 fails with error:

     Traceback (most recent call last):
      File "/usr/bin/ansible-cmdb", line 164, in <module>
        output = renderer.render(ansible.hosts, params)
      File "/usr/lib/python3.6/site-packages/ansiblecmdb/render.py", line 45, in render
        return self._render_mako(hosts, vars)
      File "/usr/lib/python3.6/site-packages/ansiblecmdb/render.py", line 62, in _render_mako
        return template.render(hosts=hosts, **vars)
      File "/usr/lib/python3.6/site-packages/mako/template.py", line 462, in render
        return runtime._render(self, self.callable_, args, data)
      File "/usr/lib/python3.6/site-packages/mako/runtime.py", line 838, in _render
        **_kwargs_for_callable(callable_, data))
      File "/usr/lib/python3.6/site-packages/mako/runtime.py", line 873, in _render_context
        _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
      File "/usr/lib/python3.6/site-packages/mako/runtime.py", line 899, in _exec_template
        callable_(context, *args, **kwargs)
      File "/usr/lib/python3.6/site-packages/ansiblecmdb/data/tpl/html_fancy.tpl", line 32, in render_body
        <% html_host_overview(cols, hosts, skip_empty=skip_empty, link_type=link_type) %>
      File "/usr/lib/python3.6/site-packages/ansiblecmdb/data/tpl/html_fancy_defs.html", line 260, in render_html_host_overview
        % for cnt in range(len(cols) - 1):
    TypeError: object of type 'filter' has no len()

**Comment by fboender** [comment]
Cannot reproduce.
