### ISSUE TITLE
template failing when a variable key is a number

### ISSUE THREAD

**Issue by landryb** [fboender/ansible-cmdb#144]
I have a host which has this in its vars:
```
 mapproxy_pools: {
  1: 3,
  2: 3,
  backup: 2
 }
```

ansible doesnt mind at all but ansible-cmdb trips on it:
```
Whoops, it looks like something went wrong while rendering the template.

The reported error was: AttributeError: 'int' object has no attribute 'replace'

The full error was:

    Traceback (most recent call last):
      File "/usr/bin/ansible-cmdb", line 164, in <module>
        output = renderer.render(ansible.hosts, params)
      File "/usr/lib/ansible-cmdb/ansiblecmdb/render.py", line 45, in render
        return self._render_mako(hosts, vars)
      File "/usr/lib/ansible-cmdb/ansiblecmdb/render.py", line 62, in _render_mako
        return template.render(hosts=hosts, **vars)
      File "/usr/lib/ansible-cmdb/mako/template.py", line 443, in render
        return runtime._render(self, self.callable_, args, data)
      File "/usr/lib/ansible-cmdb/mako/runtime.py", line 803, in _render
        **_kwargs_for_callable(callable_, data))
      File "/usr/lib/ansible-cmdb/mako/runtime.py", line 835, in _render_context
        _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
      File "/usr/lib/ansible-cmdb/mako/runtime.py", line 860, in _exec_template
        callable_(context, *args, **kwargs)
      File "/usr/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy.tpl", line 34, in render_body
        <% html_host_details(hosts, collapsed=collapsed, skip_empty=skip_empty) %>
      File "/usr/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy_defs.html", line 283, in render_html_host_details
        <% html_host_detail(host, collapsed=collapsed, skip_empty=skip_empty) %>
      File "/usr/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy_defs.html", line 277, in html_host_detail
        <%def name="html_host_details(hosts, collapsed=False, skip_empty=False)">
      File "/usr/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy_defs.html", line 311, in render_html_host_detail
        <% host_custvars(host, collapsed_class) %>
      File "/usr/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy_defs.html", line 288, in host_custvars
        <%def name="html_host_detail(host, collapsed=False, skip_empty=False)">
      File "/usr/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy_defs.html", line 698, in render_host_custvars
        ${r_dict(var_value)}
      File "/usr/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy_defs.html", line 687, in r_dict
        <%def name="host_custvars(host, collapsed_class)">
      File "/usr/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy_defs.html", line 78, in render_r_dict
        <th>${k.replace('ansible_', '')}</th>  
    AttributeError: 'int' object has no attribute 'replace'
```

quoting the keys "fixes" the issue, but im not sure it should be done this way..

**Comment by fboender** [comment]
I've pushed a fix that should solve this problem. Can you check if it works for you now?

Thanks for reporting it! I'm going to close the issue. If things aren't working properly for you, please don't hesitate to reopen it!
