### ISSUE TITLE
Error while parsing hosts contents: 'Traceback (most recent call last)

### ISSUE THREAD

**Issue by emanuelefilippello** [fboender/ansible-cmdb#146]
ansible 2.4.2.0
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/usr/share/ansible/modules']
ansible python module location = /usr/lib/python2.7/site-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

Error while parsing hosts contents: 'Traceback (most recent call last):
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 31, in __init__
    self.sections = self._parse_hosts_contents(hosts_contents)
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 96, in _parse_hosts_contents
    name, vars = self._parse_line_entry(line, cur_section['type'])
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 160, in _parse_line_entry
    key_values = self._parse_line_vars(line)
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 194, in _parse_line_vars
    key_values = self._parse_vars(tokens)
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 214, in _parse_vars
    k, v = token.split('=', 1)
ValueError: need more than 1 value to unpack
'. Invalid hosts file?

**Comment by fboender** [comment]
Hi Emanuele!

Which version of ansible-cmdb are you using? (You can check with `ansible-cmdb --version`). This bug should have been fixed a long time ago.

**Comment by emanuelefilippello** [comment]
Last release

**Comment by fboender** [comment]
Which exact version is that? Please include the output of "ansible-cmdb --version", so I can see if you're running from the git repo or from a packaged version. Thanks!

**Comment by emanuelefilippello** [comment]
ansible-cmdb v1.25
Thanks for support!

**Comment by fboender** [comment]
Hi Emanuele!

Unfortunately, I can't seem to reproduce this issue. Can you try bisecting your hosts file to find out which line is causing the problem? Just keep removing things from the hosts file until you're left with the line(s) that are causing the problem.
