### ISSUE TITLE
Error while parsing group_vars/all : 'TypeError: argument of type 'NoneType' is not iterable'

### ISSUE THREAD

**Issue by wittmaha** [fboender/ansible-cmdb#156]
Hi, 

i get following error when i want to parse my inventory file and the group_vars.

if i parse only the inventory file it is working. 

thank for any help in advance.

1.)
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

2.)
`ansible-cmdb v1.25`

3.)
```
Traceback (most recent call last):
  File "/bin/ansible-cmdb", line 153, in <module>
    ansible = ansiblecmdb.Ansible(args, hosts_files, options.fact_cache, debug=options.debug)
  File "/usr/lib/python2.7/site-packages/ansiblecmdb/ansible.py", line 69, in __init__
    self._parse_groupvar_dir(inventory_path)
  File "/usr/lib/python2.7/site-packages/ansiblecmdb/ansible.py", line 240, in _parse_groupvar_dir
    self.update_host(hostname, {'hostvars': invars}, overwrite=False)
  File "/usr/lib/python2.7/site-packages/ansiblecmdb/ansible.py", line 318, in update_host
    util.deepupdate(host_info, key_values, overwrite=overwrite)
  File "/usr/lib/python2.7/site-packages/ansiblecmdb/util.py", line 36, in deepupdate
    deepupdate(target[k], v, overwrite=overwrite)
  File "/usr/lib/python2.7/site-packages/ansiblecmdb/util.py", line 28, in deepupdate
    if not k in target:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by fboender** [comment]
Hi wittmaha. Thanks for the bug report!

Can you try re-running the command with the '-d' option and pasting the output here? That should include some useful debug info.

If you want to, and know how, you could also try the latest "master" branch directly from Git. Perhaps the issue is already fixed.

Regards,

**Comment by wittmaha** [comment]
Hi fboender,

sure!

```
data_dir = /usr/lib/python2.7/site-packages/ansiblecmdb/data
tpl_dir = /usr/lib/python2.7/site-packages/ansiblecmdb/data/tpl
static_dir = /usr/lib/python2.7/site-packages/ansiblecmdb/data/static
inventory files = ['/admin/ansible/dekav/inventories/prod/inventory']
template params = {'exclude_columns': None, 'data_dir': '/usr/lib/python2.7/site-packages/ansiblecmdb/data', 'log': <logging.RootLogger object at 0x7fdbd70b6690>, 'lib_dir': '/usr/lib/python2.7/site-packages/ansiblecmdb/data', 'version': '1.25', 'columns': None}
Parsing fact dir: /admin/cmdb/ansible_cmdb_output/
Reading host facts from /admin/cmdb/ansible_cmdb_output/xxxxxxx
Reading host facts from /admin/cmdb/ansible_cmdb_output/xxxxxxx
Reading host facts from /admin/cmdb/ansible_cmdb_output/xxxxxxx
Reading host facts from /admin/cmdb/ansible_cmdb_output/xxxxxxx
Reading host facts from /admin/cmdb/ansible_cmdb_output/xxxxxxx
Reading host facts from /admin/cmdb/ansible_cmdb_output/xxxxxxx
Reading host facts from /admin/cmdb/ansible_cmdb_output/xxxxxxx
Reading host facts from /admin/cmdb/ansible_cmdb_output/xxxxxxx
Reading host facts from /admin/cmdb/ansible_cmdb_output/xxxxxxx
...
...
Determining type of inventory_path /admin/ansible/xxxxxxx/inventories/xxxxxxx/inventory
/admin/ansible/xxxxxxx/inventories/xxxxxxx/inventory is a file. Handle as static inventory file
Inventory path /admin/ansible/xxxxxxx/inventories/xxxxxxx/inventory is a file. Reading as inventory.
Parsing host vars (dir): /admin/ansible/xxxxxxx/inventories/xxxxxxx/host_vars
Reading host vars from /admin/ansible/xxxxxxx/inventories/xxxxxxx/host_vars/xxxxxxx
Reading host vars from /admin/ansible/xxxxxxx/inventories/xxxxxxx/host_vars/xxxxxxx
Reading host vars from /admin/ansible/xxxxxxx/inventories/xxxxxxx/host_vars/xxxxxxx
Reading host vars from /admin/ansible/xxxxxxx/inventories/xxxxxxx/host_vars/xxxxxxx
...
...
Parsing group vars (dir): /admin/ansible/xxxxx/inventories/xxxxx/group_vars
Reading group vars from /admin/ansible/xxxxxx/inventories/xxxxxx/group_vars/xxxxxxxxx
Reading group vars from /admin/ansible/xxxxxxxxx/inventories/xxxxx/group_vars/xxxxxxxxx
Reading group vars from /admin/ansible/xxxxxxxxx/inventories/xxxxx/group_vars/xxxxxxxxx
Reading group vars from /admin/ansible/xxxxxxxxx/inventories/xxxxxx/group_vars/xxxxxxxxx
...
...
...
Reading group vars from /admin/ansible/xxxxxx/inventories/xxxxx/group_vars/all
Traceback (most recent call last):
  File "/bin/ansible-cmdb", line 153, in <module>
    ansible = ansiblecmdb.Ansible(args, hosts_files, options.fact_cache, debug=options.debug)
  File "/usr/lib/python2.7/site-packages/ansiblecmdb/ansible.py", line 69, in __init__
    self._parse_groupvar_dir(inventory_path)
  File "/usr/lib/python2.7/site-packages/ansiblecmdb/ansible.py", line 240, in _parse_groupvar_dir
    self.update_host(hostname, {'hostvars': invars}, overwrite=False)
  File "/usr/lib/python2.7/site-packages/ansiblecmdb/ansible.py", line 318, in update_host
    util.deepupdate(host_info, key_values, overwrite=overwrite)
  File "/usr/lib/python2.7/site-packages/ansiblecmdb/util.py", line 36, in deepupdate
    deepupdate(target[k], v, overwrite=overwrite)
  File "/usr/lib/python2.7/site-packages/ansiblecmdb/util.py", line 28, in deepupdate
    if not k in target:
TypeError: argument of type 'NoneType' is not iterable
``

It seems it is the "all" file isnt it?

Thanks !

Harry

**Comment by wittmaha** [comment]
The issue is solved. I had some empty hosts_var files in my inventory folder. I deleted them and it seems to work now.

Thanks for your help @fboender!

**Comment by fboender** [comment]
Thanks for figuring out where it went wrong wittmaha! I've implemented a check to prevent ansible-cmdb from crashing on empty host vars.
