### ISSUE TITLE
TypeError: 'Undefined' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by lalkrishnak** [fboender/ansible-cmdb#160]
_

> ansible 2.3.2.0
> python version 2.7.5
> ansible-cmdb 1.26

_

I'm getting below error while executing _ansible-cmdb -t html_fancy_split_detail Common/ > test.html_ command.

_
> config_dir = /etc/ansible/
> data_dir = /usr/local/lib/ansible-cmdb/ansiblecmdb/data
> tpl_dir = /usr/local/lib/ansible-cmdb/ansiblecmdb/data/tpl
> static_dir = /usr/local/lib/ansible-cmdb/ansiblecmdb/data/static
> inventory files = None
> template params = {'exclude_columns': None, 'data_dir': '/usr/local/lib/ansible-cmdb/ansiblecmdb/data', 'log': <logging.RootLogger object at 0x1b25950>, 'lib_dir': '/usr/local/lib/ansible-cmdb/ansiblecmdb/data', 'version': 'MASTER', 'columns': None}
> Parsing fact dir: Common/
> Reading host facts from Common/localhost
> 
> Whoops, it looks like something went wrong while rendering the template.
> 
> The reported error was: TypeError: 'Undefined' object has no attribute '__getitem__'
> 
> The full error was:
>     
>     Traceback (most recent call last):
>       File "/usr/local/bin/../lib/ansible-cmdb/ansible-cmdb.py", line 177, in <module>
>         output = renderer.render(ansible.hosts, params)
>       File "/usr/local/lib/ansible-cmdb/ansiblecmdb/render.py", line 42, in render
>         return self._render_mako(hosts, vars)
>       File "/usr/local/lib/ansible-cmdb/ansiblecmdb/render.py", line 59, in _render_mako
>         return template.render(hosts=hosts, **vars)
>       File "/usr/local/lib/ansible-cmdb/mako/template.py", line 443, in render
>         return runtime._render(self, self.callable_, args, data)
>       File "/usr/local/lib/ansible-cmdb/mako/runtime.py", line 803, in _render
>         **_kwargs_for_callable(callable_, data))
>       File "/usr/local/lib/ansible-cmdb/mako/runtime.py", line 835, in _render_context
>         _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
>       File "/usr/local/lib/ansible-cmdb/mako/runtime.py", line 860, in _exec_template
>         callable_(context, *args, **kwargs)
>       File "/usr/local/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy_split_detail.tpl", line 18, in render_body
>         <% html_header(host['name'], local_js, res_url) %>
>     TypeError: 'Undefined' object has no attribute '__getitem__'
>     
> The output is probably not correct.
> 
> You can report a bug on the issue tracker:
> 
>   https://github.com/fboender/ansible-cmdb/issues
> 
> Please include the debugging output (-d switch) in the report!
> 
> If you can, also include the hosts file and the facts file for the last host
> that rendered properly ('Rendering host...' in the output. If these files must
> remain confidential, you can send them to ferry.boender@gmail.com instead._

The html_fancy and html_fancy_split_overview templates are working as expected. 

Does anyone knows what can be the problem here?

**Comment by lalkrishnak** [comment]
Hi,
The html_fancy_split template is creating an empty html page when I execute 
ansible-cmdb -t html_fancy_split Common/ > test.html

Only html_fancy is working as expected.  Any idea?

**Comment by fboender** [comment]
That's correct. The html_fancy_split template generates one file per host, plus an index file. As such, it's not possible to correctly write output by redirection. Instead:

> [the html_fancy_split] template is basically the same as the html_fancy template, but it generates a cmdb/ directory with an index.html file and a separate html file for each host's details.

You should find a 'cmdb' dir in the dir where you ran ansible-cmdb.
