### ISSUE TITLE
Cannot use `pipsi install ansible-cmdb`

### ISSUE THREAD

**Issue by mgedmin** [fboender/ansible-cmdb#190]
[pipsi](https://pypi.org/project/pipsi/) is a tool that creates virtualenvs and symlinks tools into your PATH.  E.g.

    pipsi install ansible-cmdb

is roughly equivalent to

    virtualenv ~/.local/venvs/ansible-cmdb
    ~/.local/venvs/ansible-cmdb/bin/pip install ansible-cmdb
    ln -s ~/.local/venvs/ansible-cmdb/bin/ansible-cmdb ~/.local/bin/ansible-cmdb

Unfortunately this breaks ansible-cmdb's wrapper script:

```
$ which ansible-cmdb
/home/mg/.local/bin/ansible-cmdb

$ ansible-cmdb --help
Couldn't find /home/mg/.local/bin/ansible-cmdb.py in . or /home/mg/.local/bin/../lib/ansible-cmdb/ or /home/mg/.local/bin/../lib/ansiblecmdb/ (cwd=/home/mg)
```

**Comment by fboender** [comment]
Hey Marius,

Sorry for the late reply. I've been quite busy. I'll review the pull request soon (looks good at first sight) and apply it if it doesn't break any of the other distribution methods.

**Comment by mgedmin** [comment]
The same problem happens if I try to use `pipx install ansible-cmd`.  (pipx is a pipsi replacement, since pipsi is no longer maintained.)

**Comment by DevEvangit** [comment]
Have the same problem.
Traceback (most recent call last):
  File "/bin/../lib/ansiblecmdb/ansible-cmdb.py", line 19, in <module>
    from mako import exceptions
when i'm running command: ansible-cmdb -t html_fancy_split -p local_js=1 out /
Errors from PIP installer:
Traceback (most recent call last):
  File "/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3.4/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.4/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.4/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3.4/site-packages/pip/_internal/cli/cmdoptions.py", line 28, in <module>
    from pip._internal.models.target_python import TargetPython
  File "/usr/lib/python3.4/site-packages/pip/_internal/models/target_python.py", line 4, in <module>
    from pip._internal.utils.misc import normalize_version_info
  File "/usr/lib/python3.4/site-packages/pip/_internal/utils/misc.py", line 20, in <module>
    from pip._vendor import pkg_resources
  File "/usr/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 92, in <module>
    raise RuntimeError("Python 3.5 or later is required")
RuntimeError: Python 3.5 or later is required
Errors: 
 

uninstall python and reinstall it again. ??
it did not work. 

Any ideers for solution?

**Comment by voondo** [comment]
FYI the problem has been fixed with the version 1.31 
I was using the workaround proposed by mgedmin (thanks!) but I no longer have to use it.

**Comment by fboender** [comment]
Hm, I got a comment notification via email from Romain Lalaut:

> FYI the problem has been fixed with the version 1.31
> I was using the workaround proposed by mgedmin (thanks!) but I no longer have to use it.

But I don't see that comment here? I'm going to close this issue in the assumption that this is fixed. I'll be merging mgeadmin's setuptools entry point PR pretty soon, which should get rid of these problems once and for all.

**Comment by voondo** [comment]
Hi, I thought the problem was fixed but it was not. Thus I removed my comment but didn't think about the notifications. Sorry about the confusion...

**Comment by fboender** [comment]
No worries. I'm reopening this issue.

**Comment by gdevenyi** [comment]
Any progress here? Still a bug as of today.

**Comment by FrankVanDamme** [comment]
Similarly
```

$ pipx run ansible-cmdb

Traceback (most recent call last):
  File "/home/me/.local/pipx/.cache/a213a075564eaf4/bin/../lib/ansiblecmdb/ansible-cmdb.py", line 20, in <module>
    import ansiblecmdb
ModuleNotFoundError: No module named 'ansiblecmdb'
```
