### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by maravtdm** [fboender/ansible-cmdb#227]
Today, ansible-cmdb doesn't work anymore, but I really don't know why
It's a CentOS 8 with python 3
$ **python -V**                                                                                                                                                                                       
Python 3.6.8

And the output of ansible-cmdb (with debug enable) :
**$ ansible-cmdb -i inventory fact_all/ > hosts_all.html**
Determining type of inventory_path inventory
inventory is a file. Handle as static inventory file
Inventory path inventory is a file. Reading as inventory.
Error while parsing hosts contents: 'Traceback (most recent call last):
  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/parser.py", line 28, in __init__
    self.sections = self._parse_hosts_contents(hosts_contents)
  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/parser.py", line 93, in _parse_hosts_contents
    name, vars = self._parse_line_entry(line, cur_section['type'])
  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/parser.py", line 157, in _parse_line_entry
    key_values = self._parse_line_vars(line)
  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/parser.py", line 191, in _parse_line_vars
    key_values = self._parse_vars(tokens)
  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/parser.py", line 211, in _parse_vars
    k, v = token.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
'. Invalid hosts file?
Parsing host vars (dir): host_vars
No such dir host_vars
Parsing group vars (dir): group_vars
No such dir group_vars

In the documentation : 
"If host_vars and group_vars directories exist at that location, they will be included automatically."
But I don't have any of those directories

Can you help ?

**Comment by maravtdm** [comment]
My bad ...
An incorrect value in the inventory file
Sorry for the inconvenience
