### ISSUE TITLE
KeyError: u'ansible_ovs-system'

### ISSUE THREAD

**Issue by Atoms** [fboender/ansible-cmdb#3]
Xenserver 6.5 inventory ansible_interfaces:

        "ansible_interfaces": [
            "eth0",.
            "eth3",.
            "lo",.
            "ovs-system",.
            "eth2",.
            "vif1.0",.
            "eth1",.
            "xenbr5",.
            "xenbr4",.
            "eth5",.
            "eth4",.
            "xenbr1",.
            "xenbr0",.
            "xenbr3",.
            "xenbr2"
        ],. 

$ ansible-cmdb  out/ > cmdb/overview.html
Traceback (most recent call last):
  File "/usr/local/bin/ansible-cmdb", line 134, in <module>
    sys.stdout.write(mytemplate.render(hosts=ansible.hosts))
  File "/usr/lib/python2.7/site-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 783, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 815, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/site-packages/mako/runtime.py", line 841, in _exec_template
    callable_(context, *args, **kwargs)
  File "_usr_local_lib_ansible_cmdb_html_fancy_tpl", line 335, in render_body
KeyError: u'ansible_ovs-system'

if i remove ovs-system ansible-cmdb works

**Comment by fboender** [comment]
Hey Atoms,

Thanks for your bug report! I've fixed this issue in the master branch on Github. The fix will be included in the v1.2 release, which I will release soon.

I'm closing this issue. If you're still experiencing problems, please reopen the issue so we can have a further look.

Regards,

Ferry
