### ISSUE TITLE
UnicodeDecodeError while unicode character in hosts comment

### ISSUE THREAD

**Issue by zlowly** [fboender/ansible-cmdb#47]
Exception thrown after put some chinese characters as host comment in my hosts file :
```
ansible-cmdb -i /home/ansible/hosts -d out/ > index.html
data_dir = /usr/lib/ansible-cmdb/ansiblecmdb/data
tpl_dir = /usr/lib/ansible-cmdb/ansiblecmdb/data/tpl
static_dir = /usr/lib/ansible-cmdb/ansiblecmdb/data/static
Params
------------------------------------------------------------
{'columns': None,
 'data_dir': '/usr/lib/ansible-cmdb/ansiblecmdb/data',
 'lib_dir': '/usr/lib/ansible-cmdb/ansiblecmdb/data',
 'local_js': '1',
 'version': '1.9'}
Hosts
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/ansible-cmdb", line 91, in <module>
    sys.stdout.write(mytemplate.render(hosts=ansible.hosts, **params).encode('utf-8'))
  File "/usr/lib/ansible-cmdb/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/ansible-cmdb/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/ansible-cmdb/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/ansible-cmdb/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "_usr_lib_ansible_cmdb_ansiblecmdb_data_tpl_html_fancy_tpl", line 212, in render_body
  File "_usr_lib_ansible_cmdb_ansiblecmdb_data_tpl_html_fancy_tpl", line 50, in col_comment
  File "_usr_lib_ansible_cmdb_ansiblecmdb_data_tpl_html_fancy_tpl", line 650, in render_col_comment
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```

**Comment by fboender** [comment]
Hey zlowly! I've commited a fix for this problem. Can you verify that it fixes things for you?

**Comment by zlowly** [comment]
After applied the fix, I got another error msg:
```
$ansible-cmdb -p local_js=1 -i /home/ansible/hosts -d out/ > index.html
Traceback (most recent call last):
  File "/usr/bin/ansible-cmdb", line 20, in <module>
    import ansiblecmdb
  File "/usr/lib/ansible-cmdb/ansiblecmdb/__init__.py", line 1, in <module>
    from .parser import HostsParser, DynInvParser
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 4, in <module>
    if sys.version_info.major == 2:
AttributeError: 'tuple' object has no attribute 'major'
```
PS:My OS is CentOS 6.6 and running python 2.6.6.

**Comment by fboender** [comment]
Ah, Python v2.6. I didn't test against that. I've pushed a new commit that should fix the issue. Could you check again?

**Comment by zlowly** [comment]
It works now ! Thanks a lot !

**Comment by fboender** [comment]
Thanks for reporting the problem!

**Comment by ilovemysillybanana** [comment]
I'm having this problem again with the latest version, is 2.6.6 still supported?

```bash
$ ansible-cmdb -t html_fancy_split ./ out_manual/
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'major'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'minor'
/usr/local/bin/ansible-cmdb: line 22: [: : integer expression expected
Traceback (most recent call last):
  File "/usr/local/bin/../lib/ansible-cmdb/ansible-cmdb.py", line 30, in <module>
    "newer version.\n".format(sys.version))
ValueError: zero length field name in format
```

**Comment by fboender** [comment]
I'm afraid only Python v2.7 and higher are supported.
